#!/bin/bash

prg_name=`readlink -f $0`
base=`dirname $prg_name`
if [ "${base}" == "" ]; then
    base="."
fi

cd $base/tg2env/bin/
. activate

cd $base/src/convirt/web/convirt/
python setup.py compile_catalog
cd convirt/i18n/
./po-to-js.pl
cd ../public/javascript/ext2.2.1/resources/locale/
echo "cat" `pwd`"/convirt-lang-tr.js"
cat convirt-lang-tr.js
echo
deactivate

