#!/bin/bash
#
#   ConVirt   -  Copyright (c) 2008 Convirture Corp.
#   ======
#
# ConVirt is a Virtualization management tool with a graphical user
# interface that allows for performing the standard set of VM operations
# (start, stop, pause, kill, shutdown, reboot, snapshot, etc...). It
# also attempts to simplify various aspects of VM lifecycle management.
#
#
# 
#
# author :
#

nmap_ping()
{
	PORT=$1
	if [ -z "${PORT}" ]; then
		echo "${CMD}: Invalid port" 1>&2
		return 1
	fi

	shift
	HOSTS=$*
	if [ -z "${HOSTS}" ]; then
		echo "${CMD}: Invalid host(s)" 1>&2
		return 1
	fi

	NMAP=`which nmap`
	if [ -z "${NMAP}" ]; then
		echo "${CMD}: Command nmap is not installed or not in the PATH" 1>&2
		return 1
	fi

	nmap -oG - -PN -sT -p ${PORT} ${HOSTS} 2> /dev/null | grep -v "^#" | awk '/open/ { print "(" $2 ") " $3 }'
}

export CMD=`basename $0`
nmap_ping "$@"
